const APPWRITE_ENDPOINT_URL = import.meta.env.VITE_APPWRITE_ENDPOINT_URL;
const APPWRITE_PROJECT_ID = import.meta.env.VITE_APPWRITE_PROJECT_ID;
const APPWRITE_DATABASE_ID = import.meta.env.VITE_APPWRITE_DATABASE_ID;
const APPWRITE_MESSAGE_COLLECTION_ID = import.meta.env
  .VITE_APPWRITE_MESSAGE_COLLECTION_ID;

export {
  APPWRITE_ENDPOINT_URL,
  APPWRITE_PROJECT_ID,
  APPWRITE_DATABASE_ID,
  APPWRITE_MESSAGE_COLLECTION_ID,
};
